#!/bin/bash
sudo ./easyrsa gen-req @1 nopass
sudo cp pki/private/@1.key  ../../../client-configs/keys/
sudo mv pki/reqs/@1.req pki/reqs/client.req
sudo ./easyrsa import-req pki/reqs/client.req @1
sudo ./easyrsa sign-req client @1
sudo cp pki/issued/@1.crt ta.key pki/ca.crt  ../../../client-configs/keys/